### ISSUE TITLE
QUESTION: elasticsearch docker repository  - authentication required

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/service-analyzer#14]
Hi,

When i run docker-compose.yml with analyzer & elasticsearch, i'm getting following error. 

repository docker.elastic.co/elasticsearch/elasticsearch-oss ERROR: unauthorized: authentication required

I understand this is not a reportportal issue. Still do you know is there any licensing involved in using the analyzer (which in turn need elasticsearch? if not, how can i overcome the authentication issue? 

Appreciate your help!

**Comment by evjlobanova** [comment]
@mcafeerun hello! we`ve got info about this case in our release notes here https://github.com/reportportal/reportportal/releases/tag/4.0.0 . Could you please investigate section *Migration Details* the third point? 
Should you still have any questions, please let me know.

**Comment by mcafeerun** [comment]
@evjlobanova  - Thanks for your reply!

Can you lease help me clarify, where should i create this folder?
```
mkdir data/elasticsearch
chmod g+rwx data/elasticsearch
chgrp 1000 data/elasticsearch
```

Sorry to ask this again, i'm getting authentication error (not the access issue). Please see the console o/p

```
$ docker-compose -p reportportal up -d --force-recreate
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1)...
Pulling repository docker.elastic.co/elasticsearch/elasticsearch-oss
ERROR: unauthorized: authentication required
```

**Comment by pbortnik** [comment]
@mcafeerun 
by default it is stored right near you docker-compose file

**Comment by mcafeerun** [comment]
@pbortnik , Thank you!

I did performed those steps listed. Still i'm getting the same auth error. Should it be anything to do with proxy? (I'm able to pull any docker images from docker repo/registry without any issues. Only elastic search is throwing auth error)

Any thoughts?

**Comment by avarabyeu** [comment]
@mcafeerun issue is not related to reportportal. seems you violate some rules of elasticsearches's docker registry. For example, based [on this](https://github.com/elastic/elasticsearch-docker/issues/89) a can guess that ipv6 is not supported by their network.

**Comment by mcafeerun** [comment]
Thanks @avarabyeu ! I was able to resolve the issue..
