### ISSUE TITLE
Capability for non-historical analysis

### ISSUE THREAD

**Issue by nebehr** [reportportal/service-analyzer#20]
It seems, when Reportportal sends a request to analyze test items it expects from service-analyzer a response containing id of the test item being analyzed, issue type and id of another test item from the past. (btw is the API documented anywhere except [here](https://github.com/reportportal/example-custom-analyzer#analyze)?)

What if I don't want analysis results to be based on past launches? For example, if the issue type and associated issue(s) from bug tracking system can be determined from the error log alone, without looking at any historical results? Is it possible to extend service-analyzer API to make relevant_item optional AND pass back to Reportportal actual issue id(s)/URL(s), maybe even comments, along with the issue_type field?

**Comment by DzmitryHumianiuk** [comment]
Will statis patterns work for it?
https://github.com/reportportal/reportportal/issues/673
